name: test
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: pip install nbconvert ipykernel 
      - run: python -m nbconvert --to markdown --execute Untitled0.ipynb     
      - run: 
      - uses: actions/upload-artifact@v4
        with:
          path: Untitled0.md
